using System.Text.Json;

namespace AxmolHub.Core;

/// <summary>
/// Persists conversations under <c>data-root/ai/sessions/</c>: one <c>{id}.json</c> per conversation plus an
/// <c>index.json</c> of headers.
///
/// The index exists so the session picker never has to read every message body — listing is the common
/// operation and message files grow without bound. The index is a derived cache of the headers: if it is
/// missing or stale, <see cref="List"/> rebuilds it from the individual files, so it can never be the only
/// copy of anything.
/// </summary>
public sealed class ConversationStore(string root)
{
    private static readonly JsonSerializerOptions Json = new() { PropertyNameCaseInsensitive = true };

    private string SessionsDirectory => Path.Combine(root, "ai", "sessions");
    private string IndexPath => Path.Combine(SessionsDirectory, "index.json");
    private string ConversationPath(string id) => Path.Combine(SessionsDirectory, SanitizeId(id) + ".json");

    /// <summary>Session headers, pinned first then newest first. Rebuilds the index when it is absent or unreadable.</summary>
    public List<ConversationSummary> List()
    {
        if (!File.Exists(IndexPath)) return RebuildIndex();
        try
        {
            var index = JsonSerializer.Deserialize<List<ConversationSummary>>(File.ReadAllText(IndexPath), Json);
            return index is null ? RebuildIndex() : [.. Order(index)];
        }
        catch (JsonException) { return RebuildIndex(); }
    }

    /// <summary>Loads one conversation; <c>null</c> when the id is unknown.</summary>
    public Conversation? Load(string id)
    {
        var path = ConversationPath(id);
        return File.Exists(path)
            ? JsonSerializer.Deserialize<Conversation>(File.ReadAllText(path), Json)
            : null;
    }

    /// <summary>Writes a conversation and refreshes its index entry, atomically.</summary>
    public void Save(Conversation conversation)
    {
        StateStore.WriteJson(ConversationPath(conversation.Id), conversation);
        var index = List();
        index.RemoveAll(summary => summary.Id == conversation.Id);
        index.Add(ConversationSummary.From(conversation));
        StateStore.WriteJson(IndexPath, Order(index).ToList());
    }

    /// <summary>Deletes a conversation and its index entry. Deleting an unknown id is not an error.</summary>
    public void Delete(string id)
    {
        var path = ConversationPath(id);
        if (File.Exists(path)) File.Delete(path);
        var index = List();
        index.RemoveAll(summary => summary.Id == id);
        StateStore.WriteJson(IndexPath, index);
    }

    private List<ConversationSummary> RebuildIndex()
    {
        var summaries = new List<ConversationSummary>();
        if (Directory.Exists(SessionsDirectory))
        {
            foreach (var file in Directory.EnumerateFiles(SessionsDirectory, "*.json"))
            {
                if (Path.GetFileName(file).Equals("index.json", StringComparison.OrdinalIgnoreCase)) continue;
                try
                {
                    var conversation = JsonSerializer.Deserialize<Conversation>(File.ReadAllText(file), Json);
                    if (conversation is not null) summaries.Add(ConversationSummary.From(conversation));
                }
                catch (JsonException) { /* A corrupt session file is skipped, not fatal — the rest still load. */ }
            }
        }

        summaries = [.. Order(summaries)];
        StateStore.WriteJson(IndexPath, summaries);
        return summaries;
    }

    /// <summary>The single ordering rule for the session list: pinned first, then most recently updated.</summary>
    private static IEnumerable<ConversationSummary> Order(IEnumerable<ConversationSummary> summaries)
        => summaries.OrderByDescending(summary => summary.Pinned).ThenByDescending(summary => summary.UpdatedAt);

    /// <summary>
    /// Ids are GUIDs generated by <see cref="Conversation.Create"/>, but they arrive from filenames and UI
    /// callers alike — anything outside <c>[A-Za-z0-9_-]</c> is dropped so a hostile id cannot escape the
    /// sessions directory (path traversal).
    /// </summary>
    private static string SanitizeId(string id)
    {
        var clean = new string([.. id.Where(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_')]);
        if (clean.Length == 0) throw new ArgumentException("Conversation id is empty.", nameof(id));
        return clean;
    }
}
