namespace AxmolHub.Core;

/// <summary>
/// Hub 界面文案的**单一定义**。
///
/// 为什么在 Core 而不是某个 App：迁移期 WPF 版与 Avalonia 版**同时存在**（P6 才删 WPF），
/// 而两侧都要本地化。把 190 条键值复制成两份，等于让中文/英文在迁移期间静默分叉 ——
/// 恰恰是迁移期最容易顺手改文案。这与 ADR-0001 对"工具只定义一次"的要求是同一条道理：
/// 数据放 Core，各客户端只留一层薄适配（WPF 写 Application.Resources，
/// Avalonia 写 Avalonia 资源字典），任何一侧都不再拥有文案本身。
///
/// 这里**只有数据与查表**，不含任何 UI 框架类型，因此 Core 的零依赖、可离线冷构建
/// 性质不受影响。文案与界面框架无关，界面框架只决定"怎么送进资源字典"。
/// </summary>
public static class HubTexts
{
    public const string DefaultLanguage = "zh-CN";
    public const string EnglishLanguage = "en-US";

    /// <summary>未知语言一律回落到中文，而不是抛异常：语言来自设置文件，属于用户数据。</summary>
    public static string Normalize(string? language)
        => language == EnglishLanguage ? EnglishLanguage : DefaultLanguage;

    public static bool IsSupported(string? language) => language is DefaultLanguage or EnglishLanguage;

    /// <summary>键不存在时返回键本身，与 WPF 版既有行为一致（缺失文案会显式暴露，而不是显示空白）。</summary>
    public static string Get(string key, string? language) => Values.TryGetValue(key, out var value)
        ? (Normalize(language) == DefaultLanguage ? value.Chinese : value.English)
        : key;

    /// <summary>全部键。适配层靠它把文案灌进各自的资源字典。</summary>
    public static IReadOnlyCollection<string> Keys => Values.Keys;

    private static readonly Dictionary<string, (string Chinese, string English)> Values = new()
    {
        ["BuildComplete"] = ("编译完成", "Build completed"),
        ["BuildConfiguration"] = ("构建配置", "Build configuration"),
        ["ConfigurationHint"] = ("Debug：调试、断言与详细日志。Release：优化构建。两种配置的产物分别保存。", "Debug: debugging, assertions and detailed logs. Release: optimized build. Outputs are stored separately."),
        ["AndroidReleasePending"] = ("Release 使用项目发行密钥，生成已签名 APK/AAB；继续后配置包名、版本和密钥。", "Release uses your project key to produce signed APK/AAB. Configure application ID, version and signing after continuing."),
        ["AndroidReleaseSettings"] = ("Android 发行设置", "Android release settings"),
        ["LastBuildPlatform"] = ("当前构建目标", "Current build target"),
        ["ChooseBuildPlatform"] = ("选择构建平台", "Choose build platform"),
        ["BuildPlatformHint"] = ("项目源码可用于多个平台。每次构建可选择目标；Apple 平台需 macOS，Linux 需 Linux 宿主。", "Project sources support multiple platforms. Choose a target for this build; Apple platforms require macOS, Linux requires a Linux host."),
        ["Continue"] = ("继续", "Continue"),
        ["AddModules"] = ("添加模块", "Add modules"),
        ["ModulesHint"] = ("先选择引擎版本，再勾选平台。公共依赖自动合并，工具保存在 Hub 数据目录。", "Choose an engine version, then select platforms. Shared dependencies are installed once in Hub storage."),
        ["DownloadSize"] = ("下载大小", "Download size"),
        ["DiskSize"] = ("解压大小", "Extracted size"),
        ["InstallSelected"] = ("保存并安装所选", "Save and install selection"),
        ["Back"] = ("返回", "Back"),
        ["ModuleInstalled"] = ("组件已安装", "Components installed"),
        ["ModuleMissing"] = ("待安装", "Not installed"),
        ["ModuleExternal"] = ("源码已包含 · 需专用宿主", "Sources included · requires native host"),
        ["ModuleUnknownSize"] = ("由官方安装器计算", "Calculated by official installer"),
        ["ModuleTotals"] = ("新增下载 / 解压：", "Additional download / extraction:"),
        ["AvailableSpace"] = ("可用空间：", "Available space:"),
        ["DependencyHint"] = ("依赖随平台自动选择；取消勾选仅移除选择，不卸载组件。", "Dependencies follow platform selection. Deselecting does not uninstall components."),
        ["ComponentDetails"] = ("组件诊断", "Component diagnostics"),
        ["ModuleUnsupported"] = ("该引擎版本尚无经过验证的模块清单。", "No verified module profile for this engine version."),
        ["Install engine modules"] = ("安装引擎模块", "Install engine modules"),
        ["ModuleSaved"] = ("模块选择已保存；专用宿主模块仍需在对应系统配置。", "Selection saved; native-host modules require setup on their respective systems."),
        ["LocalHost"] = ("可在本机配置与构建", "Configure and build on this host"),
        ["RequiresHost"] = ("构建宿主：", "Build host:"),
        ["PlatformToolsNote"] = ("工具只从 Hub 目录检测；SDK 文件存在仍需通过配置验证。", "Tools are checked only in Hub directories; SDK files still require configure verification."),
        ["AndroidNativeNote"] = ("支持 Debug / Release APK 和 AAB；Release 使用项目密钥，设备运行需选择已授权设备。", "Supports Debug/Release APKs and AABs. Release uses your project key; select an authorized device to run the APK."),
        ["OpenOutputs"] = ("打开产物", "Open outputs"),
        ["Open build outputs"] = ("打开构建产物", "Open build outputs"),
        ["AndroidDevice"] = ("Android 设备", "Android device"),
        ["RefreshDevices"] = ("刷新设备", "Refresh devices"),
        ["Refresh Android devices"] = ("查询 Android 设备", "Query Android devices"),
        ["AndroidDeviceHint"] = ("连接设备并开启 USB 调试；在设备上允许 Hub 的调试授权。", "Connect a device with USB debugging enabled and approve Hub's debugging authorization on the device."),
        ["AndroidNoDevices"] = ("未检测到设备", "No devices detected"),
        ["SelectAndroidDevice"] = ("请刷新并选择已授权的 Android 设备。", "Refresh and select an authorized Android device."),
        ["device"] = ("已授权", "Authorized"),
        ["unauthorized"] = ("等待调试授权", "Awaiting debugging authorization"),
        ["offline"] = ("离线", "Offline"),
        ["Change target"] = ("切换目标平台", "Change target platform"),
        ["UwpPending"] = ("UWP 工具隔离与打包待完成", "UWP isolation and packaging pending"),
        ["Projects"] = ("项目", "Projects"),
        ["Installs"] = ("引擎", "Engines"),
        ["Toolchains"] = ("工具链", "Toolchains"),
        ["Settings"] = ("设置", "Settings"),
        ["Subtitle"] = ("开发，从这里开始", "Your development workspace"),
        ["ProjectsHint"] = ("创建、构建并运行你的 Axmol 项目。", "Create, build and run your Axmol projects."),
        ["NewProject"] = ("新建项目", "New project"),
        ["OpenExisting"] = ("添加已有项目", "Add existing project"),
        ["ProjectName"] = ("项目名称", "Project name"),
        ["Location"] = ("项目父目录", "Parent directory"),
        ["EngineVersion"] = ("引擎版本", "Engine version"),
        ["Template"] = ("官方 2D · Hello World 模板", "Official 2D · Hello World template"),
        ["Scripting"] = ("脚本方式", "Scripting"),
        ["cpp"] = ("仅 C++", "C++ only"),
        ["lua"] = ("C++ + Lua", "C++ + Lua"),
        ["ScriptingHint"] = ("Lua 项目包含 C++ 原生入口、Lua 绑定与脚本。项目创建后按选定方式开发。", "Lua projects include a C++ entry point, Lua bindings and scripts. The choice sets the initial project structure."),
        ["Create"] = ("创建项目", "Create project"),
        ["Browse"] = ("选择目录", "Browse"),
        ["Name"] = ("名称", "Name"),
        ["Version"] = ("版本", "Version"),
        ["BuildStatus"] = ("构建状态", "Build status"),
        ["LastOpened"] = ("最近打开", "Last opened"),
        ["Path"] = ("目录", "Directory"),
        ["Configure"] = ("配置", "Configure"),
        ["Build"] = ("构建", "Build"),
        ["Run"] = ("运行", "Run"),
        ["OpenFolder"] = ("打开目录", "Open folder"),
        ["RemoveFromList"] = ("移出列表", "Remove from list"),
        ["ProjectsCount"] = ("项目", "Projects"),
        ["EnginesCount"] = ("已安装引擎", "Installed engines"),
        ["Platform"] = ("目标平台", "Target platform"),
        ["EnginesHint"] = ("版本独立安装，项目始终锁定自己的引擎。", "Separate installations. Each project keeps its engine version."),
        // 刻意不写死版本号：清单里现在有六个版本，按钮上印"安装 2.11.5"会在
        // 清单变更后变成一句假话，而它旁边就是版本选择器。
        ["InstallOfficial"] = ("安装官方引擎", "Install official engine"),
        ["ChooseEngineVersion"] = ("选择引擎版本", "Choose engine version"),
        ["EngineVersionHint"] = ("每个版本独立安装到 Hub 数据目录，项目始终锁定创建时的版本。", "Each version installs independently into Hub storage. Projects keep the version they were created with."),
        ["EngineVersionNone"] = ("清单里没有可安装的引擎版本。", "The manifest declares no installable engine release."),
        ["EngineIndexRemote"] = ("版本列表来自 axmol.dev 索引。", "Version list from the axmol.dev index."),
        ["EngineIndexBuiltIn"] = ("未能获取 axmol.dev 索引，正在使用 Hub 内置列表。", "axmol.dev index unavailable. Using the built-in list."),
        ["EngineModulesUnverified"] = ("该版本尚无经过验证的模块清单：引擎可用，但“添加模块”与 Android 打包会被拒绝。", "This version has no verified module profile: the engine works, but Add modules and Android packaging are refused."),
        ["ImportEngine"] = ("导入引擎", "Import engine"),
        ["Channel"] = ("通道", "Channel"),
        ["SetDefault"] = ("设为默认", "Set default"),
        ["VerifyEngine"] = ("验证", "Verify"),
        ["Repair"] = ("修复", "Repair"),
        ["Uninstall"] = ("卸载", "Uninstall"),
        ["ToolsTitle"] = ("平台构建支持", "Platform build support"),
        ["ToolsHint"] = ("按引擎版本管理平台模块和配套工具。", "Manage platform modules and tools for each engine version."),
        ["ToolsNote"] = ("MSVC 使用微软官方安装器，需要 Windows 管理员授权。", "MSVC uses Microsoft's installer and requires Windows administrator approval."),
        ["Component"] = ("组件", "Component"),
        ["Status"] = ("状态", "Status"),
        ["Details"] = ("版本与目录", "Version and location"),
        ["Verify"] = ("重新检测", "Verify"),
        ["InstallTools"] = ("安装基础工具", "Install tools"),
        ["RunEngineSetup"] = ("运行引擎 setup.ps1", "Run engine setup.ps1"),
        ["EngineSetupHint"] = ("工具链由引擎自己安装到引擎目录的 tools/external。这一步会写入用户级 PATH 与 AX_ROOT，并可能请求提权（UAC）——与引擎官方流程一致。", "The engine installs its own toolchain into <engine>/tools/external. This writes the user PATH and AX_ROOT and may request elevation (UAC) — the same as the engine's official flow."),
        ["InstallSdk"] = ("安装 Windows SDK", "Install Windows SDK"),
        ["InstallMsvc"] = ("安装 MSVC", "Install MSVC"),
        ["SettingsHint"] = ("按你的习惯设置语言、存储目录与编辑器。", "Choose your language, storage and editors."),
        ["Language"] = ("界面语言", "Interface language"),
        ["LanguageHint"] = ("切换立即生效，重启后保留。", "Applies immediately and is remembered."),
        ["Storage"] = ("存储与项目", "Storage and projects"),
        ["DataDirectory"] = ("Hub 数据目录", "Hub data directory"),
        ["DataHint"] = ("引擎、工具链、缓存与日志存放于此。切换目录不会移动现有文件。", "Engines, tools, cache and logs. Changing directories does not move existing files."),
        ["DefaultProjectDirectory"] = ("默认项目目录", "Default project directory"),
        ["ProjectDirectoryHint"] = ("创建新项目时默认使用此目录。", "Default parent directory for new projects."),
        ["Editors"] = ("代码编辑器", "Code editors"),
        ["SelectEditor"] = ("选择程序", "Choose executable"),
        ["NotSelected"] = ("尚未选择", "Not selected"),
        ["EditorHint"] = ("选择已安装的编辑器，用于打开项目。", "Choose an installed editor to open projects."),
        ["DefaultEngine"] = ("默认引擎", "Default engine"),
        ["NoDefault"] = ("尚未安装引擎", "No engine installed"),
        ["LogTitle"] = ("活动与构建日志", "Activity and build log"),
        ["CopyError"] = ("复制错误", "Copy error"),
        ["OpenLogs"] = ("打开日志", "Open logs"),
        ["Cancel"] = ("取消", "Cancel"),
        ["Ready"] = ("准备就绪", "Ready"),
        ["Done"] = ("已完成", "completed"),
        ["Cancelled"] = ("已取消", "cancelled"),
        ["Failed"] = ("失败", "Failed"),
        ["Working"] = ("处理中", "Working"),
        ["Download"] = ("下载中", "Downloading"),
        ["EmptyProjects"] = ("还没有项目。创建第一个项目，开始开发。", "No projects yet. Create your first project to get started."),
        ["EmptyEngines"] = ("还没有引擎。安装或导入 Axmol。", "No engines yet. Install or import Axmol."),
        ["Installed"] = ("已安装", "Installed"),
        ["Missing"] = ("未安装", "Missing"),
        ["Broken"] = ("需要修复", "Broken"),
        ["Unknown"] = ("未检测", "Unknown"),
        ["Checking"] = ("检测中", "Checking"),
        ["Installing"] = ("安装中", "Installing"),
        ["UpdateAvailable"] = ("有更新", "Update available"),
        ["Not built"] = ("未构建", "Not built"),
        ["Succeeded"] = ("构建成功", "Succeeded"),
        ["Configured"] = ("已配置", "Configured"),
        ["Configuring"] = ("配置中", "Configuring"),
        ["Building"] = ("构建中", "Building"),
        ["Select a project first."] = ("请先选择项目。", "Select a project first."),
        ["Select an engine first."] = ("请先选择引擎。", "Select an engine first."),
        ["Install or import an engine first."] = ("请先安装或导入引擎。", "Install or import an engine first."),
        ["Build successfully before Run."] = ("请先成功构建，再运行。", "Build successfully before Run."),
        ["Select VS Code executable in Settings first."] = ("请先在设置中选择 VS Code。", "Select VS Code executable in Settings first."),
        ["Select Visual Studio devenv.exe in Settings first."] = ("请先在设置中选择 Visual Studio。", "Select Visual Studio devenv.exe in Settings first."),
        ["Verify toolchains"] = ("检测工具链", "Verify toolchains"),
        ["Import engine"] = ("导入引擎", "Import engine"),
        ["Install official engine"] = ("安装官方引擎", "Install official engine"),
        ["Create project"] = ("创建项目", "Create project"),
        ["Open project"] = ("添加项目", "Add project"),
        ["Configure CMake"] = ("配置 CMake", "Configure CMake"),
        ["Build project"] = ("构建项目", "Build project"),
        ["Run project"] = ("运行项目", "Run project"),
        ["Install managed tools"] = ("安装基础工具", "Install tools"),
        ["Install Windows SDK"] = ("安装 Windows SDK", "Install Windows SDK"),
        ["Install MSVC Build Tools"] = ("安装 MSVC", "Install MSVC"),
        ["Set default engine"] = ("设置默认引擎", "Set default engine"),
        ["Verify engine"] = ("验证引擎", "Verify engine"),
        ["Remove engine from list"] = ("移出引擎列表", "Remove engine from list"),
        ["Remove project from list"] = ("移出项目列表", "Remove project from list"),
        ["Open project folder"] = ("打开项目目录", "Open project folder"),
        ["Open engine folder"] = ("打开引擎目录", "Open engine folder"),
        ["Open VS Code"] = ("打开 VS Code", "Open VS Code"),
        ["Open Visual Studio"] = ("打开 Visual Studio", "Open Visual Studio"),
        ["Select Axmol engine root"] = ("选择 Axmol 引擎目录", "Select Axmol engine root"),
        ["Select Axmol project folder"] = ("选择 Axmol 项目目录", "Select Axmol project folder"),
        ["Select parent location"] = ("选择项目父目录", "Select parent directory"),
        ["Select data directory"] = ("选择 Hub 数据目录", "Select Hub data directory"),
        ["Select default project directory"] = ("选择默认项目目录", "Select default project directory"),
        ["MsvcActive"] = ("微软安装器运行中，请批准 Windows 授权；取消请使用安装器界面。", "Microsoft installer is running. Approve Windows UAC; cancel in the installer."),
        ["Cancelling"] = ("正在取消，请等待进程停止后再关闭。", "Cancelling. Close again when the process stops."),
        ["ErrorHint"] = ("操作失败，详细原因已记录在日志中。", "Operation failed. Details are recorded in the log."),
        ["OperationFailed"] = ("操作失败", "Operation failed"),
        ["BuildProgress"] = ("构建进度", "Build progress"),
        ["BuildPreparing"] = ("准备构建", "Preparing build"),
        ["BuildConfiguring"] = ("配置项目", "Configuring project"),
        ["BuildCompiling"] = ("编译代码", "Compiling code"),
        ["BuildPackaging"] = ("打包应用", "Packaging application"),
        ["BuildVerifying"] = ("校验产物", "Verifying output"),
        ["BuildElapsed"] = ("已用时间", "Elapsed"),
        ["BuildProgressHint"] = ("百分比显示当前编译阶段的进度；配置、打包和校验时显示活动进度。", "Percentage shows the current compilation stage. Configuration, packaging and verification use an activity indicator."),
        ["ProjectAlreadyExists"] = ("项目目录已存在，无法创建同名项目。", "The project destination already exists. Cannot create a project at the same location."),
        ["ProjectAlreadyExistsAction"] = ("请修改项目名称或选择其他目录。若要使用现有项目，请点击“添加已有项目”。", "Change the project name or choose another directory. To use the existing project, click Add existing project."),
        ["EngineMissing"] = ("项目所需引擎未安装，请前往引擎页面安装或导入。", "Required engine is missing. Install or import it on the Engines page."),
        ["Managed MSVC v143"] = ("MSVC v143", "MSVC v143"),
        ["Managed Windows SDK"] = ("Windows SDK", "Windows SDK"),
        ["Axmol shader compiler"] = ("着色器编译器", "Shader compiler"),
        ["Python (optional for Windows C++)"] = ("Python（Windows C++ 可选）", "Python (optional for Windows C++)"),
        ["Repair engine"] = ("修复引擎", "Repair engine"),
        ["Uninstall engine"] = ("卸载引擎", "Uninstall engine"),
        ["DataChanged"] = ("数据目录已切换", "Data directory changed"),
        ["DefaultProjectsChanged"] = ("默认项目目录已保存", "Default project directory saved"),
        ["PageNotMigrated"] = ("该页面尚未迁移到 Avalonia 版（P5 进行中）。", "This page has not been migrated to the Avalonia build yet (P5 in progress)."),
        ["WaitForOperation"] = ("请先等当前操作结束或取消它，再切换数据目录。", "Wait for the active operation to finish or cancel it before changing the data directory."),
        ["LocalPathRequired"] = ("选中的位置没有本地路径，请选择本机磁盘上的位置。", "The selected location has no local path. Choose a location on this PC."),
        ["Select devenv.exe"] = ("选择 devenv.exe", "Select devenv.exe"),
        ["Select Code.exe"] = ("选择 Code.exe", "Select Code.exe"),
        ["Choose devenv.exe"] = ("请选择 devenv.exe。", "Choose devenv.exe."),
        ["Choose Code.exe"] = ("请选择 Code.exe。", "Choose Code.exe."),
    };
}
