namespace AxmolHub.Core;

/// <summary>
/// Hub 界面文案的**单一定义**。
///
/// 为什么在 Core 而不是某个 App：迁移期 WPF 版与 Avalonia 版**同时存在**（P6 才删 WPF），
/// 而两侧都要本地化。把 190 条键值复制成两份，等于让中文/英文在迁移期间静默分叉 ——
/// 恰恰是迁移期最容易顺手改文案。这与 ADR-0001 对"工具只定义一次"的要求是同一条道理：
/// 数据放 Core，各客户端只留一层薄适配（WPF 写 Application.Resources，
/// Avalonia 写 Avalonia 资源字典），任何一侧都不再拥有文案本身。
///
/// 这里**只有数据与查表**，不含任何 UI 框架类型，因此 Core 的零依赖、可离线冷构建
/// 性质不受影响。文案与界面框架无关，界面框架只决定"怎么送进资源字典"。
/// </summary>
public static class HubTexts
{
    public const string ChineseLanguage = "zh-CN";
    public const string EnglishLanguage = "en-US";

    /// <summary>
    /// 没有设置、或设置里是一个不认识的值时使用的语言。
    ///
    /// **2026-10-03 由 <c>zh-CN</c> 改为 <c>en-US</c>**：起步语言是中文时，
    /// 在没装 CJK 字体的 Linux（最小化安装的 Ubuntu 默认如此）上整片界面会显示成空白/方块，
    /// 用户连"去设置里换成英文"都做不到 —— 设置页的语言下拉里那一项本身就是中文。
    /// 英文在任何系统上都能显示，所以拿它当冷启动的兜底。
    ///
    /// 注意它**不等于"中文"**。判断"当前是不是中文"要用 <see cref="ChineseLanguage"/>：
    /// 这两个常量以前是同一个值，混用无所谓；现在值不同了，混用会让中文界面上出现英文硬编码文案。
    /// </summary>
    public const string DefaultLanguage = EnglishLanguage;

    /// <summary>未知语言一律回落到 <see cref="DefaultLanguage"/>，而不是抛异常：语言来自设置文件，属于用户数据。</summary>
    public static string Normalize(string? language)
        => language == ChineseLanguage ? ChineseLanguage : DefaultLanguage;

    public static bool IsSupported(string? language) => language is ChineseLanguage or EnglishLanguage;

    /// <summary>键不存在时返回键本身，与 WPF 版既有行为一致（缺失文案会显式暴露，而不是显示空白）。</summary>
    public static string Get(string key, string? language) => Values.TryGetValue(key, out var value)
        ? (Normalize(language) == ChineseLanguage ? value.Chinese : value.English)
        : key;

    /// <summary>全部键。适配层靠它把文案灌进各自的资源字典。</summary>
    public static IReadOnlyCollection<string> Keys => Values.Keys;

    private static readonly Dictionary<string, (string Chinese, string English)> Values = new()
    {
        ["BuildComplete"] = ("编译完成", "Build completed"),
        ["BuildConfiguration"] = ("构建配置", "Build configuration"),
        ["ConfigurationHint"] = ("Debug：调试、断言与详细日志。Release：优化构建。两种配置的产物分别保存。", "Debug: debugging, assertions and detailed logs. Release: optimized build. Outputs are stored separately."),
        ["AndroidReleasePending"] = ("Release 使用项目发行密钥，生成已签名 APK/AAB；继续后配置包名、版本和密钥。", "Release uses your project key to produce signed APK/AAB. Configure application ID, version and signing after continuing."),
        ["AndroidReleaseSettings"] = ("Android 发行设置", "Android release settings"),
        ["LastBuildPlatform"] = ("当前构建目标", "Current build target"),
        ["ChooseBuildPlatform"] = ("选择构建平台", "Choose build platform"),
        ["BuildPlatformHint"] = ("项目源码可用于多个平台。每次构建可选择目标；Apple 平台需 macOS，Linux 需 Linux 宿主。", "Project sources support multiple platforms. Choose a target for this build; Apple platforms require macOS, Linux requires a Linux host."),
        ["Continue"] = ("继续", "Continue"),
        ["DownloadSize"] = ("下载大小", "Download size"),
        ["InstallSelected"] = ("保存并安装所选", "Save and install selection"),
        ["Back"] = ("返回", "Back"),
        ["ComponentDetails"] = ("组件诊断", "Component diagnostics"),
        ["LocalHost"] = ("可在本机配置与构建", "Configure and build on this host"),
        ["RequiresHost"] = ("构建宿主：", "Build host:"),
        ["PlatformToolsNote"] = ("工具只从 Hub 目录检测；SDK 文件存在仍需通过配置验证。", "Tools are checked only in Hub directories; SDK files still require configure verification."),
        ["AndroidNativeNote"] = ("支持 Debug / Release APK 和 AAB；Release 使用项目密钥，设备运行需选择已授权设备。", "Supports Debug/Release APKs and AABs. Release uses your project key; select an authorized device to run the APK."),
        ["OpenOutputs"] = ("打开产物", "Open outputs"),
        ["Open build outputs"] = ("打开构建产物", "Open build outputs"),
        ["AndroidDevice"] = ("Android 设备", "Android device"),
        ["RefreshDevices"] = ("刷新设备", "Refresh devices"),
        ["Refresh Android devices"] = ("查询 Android 设备", "Query Android devices"),
        ["AndroidDeviceHint"] = ("连接设备并开启 USB 调试；在设备上允许 Hub 的调试授权。", "Connect a device with USB debugging enabled and approve Hub's debugging authorization on the device."),
        ["AndroidNoDevices"] = ("未检测到设备", "No devices detected"),
        ["SelectAndroidDevice"] = ("请刷新并选择已授权的 Android 设备。", "Refresh and select an authorized Android device."),
        ["device"] = ("已授权", "Authorized"),
        ["unauthorized"] = ("等待调试授权", "Awaiting debugging authorization"),
        ["offline"] = ("离线", "Offline"),
        ["Change target"] = ("切换目标平台", "Change target platform"),
        ["UwpPending"] = ("UWP 工具隔离与打包待完成", "UWP isolation and packaging pending"),
        ["Projects"] = ("项目", "Projects"),
        ["Installs"] = ("引擎", "Engines"),
        ["Toolchains"] = ("工具链", "Toolchains"),
        ["Settings"] = ("设置", "Settings"),
        ["Subtitle"] = ("开发，从这里开始", "Your development workspace"),
        ["ProjectsHint"] = ("创建、构建并运行你的 Axmol 项目。", "Create, build and run your Axmol projects."),
        ["NewProject"] = ("新建项目", "New project"),
        ["OpenExisting"] = ("添加已有项目", "Add existing project"),
        ["ProjectName"] = ("项目名称", "Project name"),
        ["Location"] = ("项目父目录", "Parent directory"),
        ["EngineVersion"] = ("引擎版本", "Engine version"),
        ["Template"] = ("官方 2D · Hello World 模板", "Official 2D · Hello World template"),
        ["Scripting"] = ("脚本方式", "Scripting"),
        ["cpp"] = ("仅 C++", "C++ only"),
        ["lua"] = ("C++ + Lua", "C++ + Lua"),
        ["ScriptingHint"] = ("Lua 项目包含 C++ 原生入口、Lua 绑定与脚本。项目创建后按选定方式开发。", "Lua projects include a C++ entry point, Lua bindings and scripts. The choice sets the initial project structure."),
        ["Create"] = ("创建项目", "Create project"),
        ["Browse"] = ("选择目录", "Browse"),
        ["Name"] = ("名称", "Name"),
        ["Version"] = ("版本", "Version"),
        ["BuildStatus"] = ("构建状态", "Build status"),
        ["LastOpened"] = ("最近打开", "Last opened"),
        ["Path"] = ("目录", "Directory"),
        ["Configure"] = ("配置", "Configure"),
        ["Build"] = ("构建", "Build"),
        ["Run"] = ("运行", "Run"),
        ["OpenFolder"] = ("打开目录", "Open folder"),
        ["RemoveFromList"] = ("移出列表", "Remove from list"),
        ["ProjectsCount"] = ("项目", "Projects"),
        ["EnginesCount"] = ("已安装引擎", "Installed engines"),
        ["Platform"] = ("目标平台", "Target platform"),
        ["EnginesHint"] = ("版本独立安装，项目始终锁定自己的引擎。", "Separate installations. Each project keeps its engine version."),
        // 刻意不写死版本号：清单里现在有六个版本，按钮上印"安装 2.11.5"会在
        // 清单变更后变成一句假话，而它旁边就是版本选择器。
        ["InstallOfficial"] = ("安装官方引擎", "Install official engine"),
        ["ChooseEngineVersion"] = ("选择引擎版本", "Choose engine version"),
        ["EngineVersionHint"] = ("每个版本独立安装到 Hub 数据目录，项目始终锁定创建时的版本。", "Each version installs independently into Hub storage. Projects keep the version they were created with."),
        ["EngineVersionNone"] = ("清单里没有可安装的引擎版本。", "The manifest declares no installable engine release."),
        ["EngineIndexRemote"] = ("版本列表来自 axmol.dev 索引。", "Version list from the axmol.dev index."),
        ["EngineIndexBuiltIn"] = ("未能获取 axmol.dev 索引，正在使用 Hub 内置列表。", "axmol.dev index unavailable. Using the built-in list."),
        ["EngineRecipeUnverified"] = ("该版本尚无经过验证的打包配方：引擎可用，但 Android 打包会被拒绝。", "This version has no verified packaging recipe: the engine works, but Android packaging is refused."),
        ["DownloadSource"] = ("引擎下载源", "Engine download source"),
        ["DownloadSourceHint"] = ("引擎发布包从哪里下载。镜像提供的是同一个文件，下载后仍按 SHA-256 校验；只影响安装引擎，不改变引擎自己拉取依赖的镜像。", "Where engine release packages are downloaded from. Mirrors serve the same file and SHA-256 verification still applies. This affects engine installs only, not the mirror the engine itself fetches from."),
        ["DownloadSourceGitHub"] = ("GitHub（官方）", "GitHub (official)"),
        ["DownloadSourceAtomGit"] = ("AtomGit（镜像）", "AtomGit (mirror)"),
        ["DownloadSourceCustom"] = ("自定义", "Custom"),
        ["CustomDownloadSource"] = ("自定义下载地址", "Custom download URL"),
        ["CustomDownloadSourceHint"] = ("可填主机（例如 https://atomgit.com，只替换官方地址的域名），或含 {version} 的完整模板（例如 https://example.com/axmol/axmol-{version}.zip）。", "Enter an origin (e.g. https://atomgit.com, which replaces only the official host) or a full template containing {version} (e.g. https://example.com/axmol/axmol-{version}.zip)."),
        ["CustomUrlRequired"] = ("选择了自定义下载源，但地址为空。", "Custom download source is selected, but the URL is empty."),
        ["CustomUrlInvalid"] = ("自定义下载源无效：请填写 https 主机地址，或含 {version} 的 https 模板。", "Invalid custom download source: enter an https origin, or an https template containing {version}."),
        ["Mirror"] = ("镜像", "Mirror"),
        ["SwitchMirror"] = ("切换镜像", "Switch mirror"),
        ["SwitchEngineMirror"] = ("切换引擎镜像", "Switch engine mirror"),
        ["MirrorHint"] = ("镜像决定引擎拉取依赖与工具的来源，写在引擎目录里：v3 写 1k/.env 的 active_mirror（可选值来自 1k/sources.json），v2 只支持用空文件 1k/.gitee 切到 gitee。切换后对随后的 setup 与构建生效。", "The mirror decides where the engine fetches dependencies and tools, and it is stored inside the engine tree: v3 writes active_mirror in 1k/.env (the choices come from 1k/sources.json), v2 only supports switching to gitee via an empty 1k/.gitee file. The change applies to later setup and builds."),
        ["MirrorStatusFormat"] = ("镜像：{0}", "Mirror: {0}"),
        ["MirrorNoEngine"] = ("未选择引擎", "No engine selected"),
        ["MirrorUnknown"] = ("无法识别该引擎的镜像方式（需要 1k/.env 或 1k/.gitee）。", "This engine's mirror mechanism is not recognized (1k/.env or 1k/.gitee required)."),
        ["MirrorFallbackNote"] = ("某些依赖没有配置该镜像时，引擎会自动回退到 origin。", "The engine falls back to origin for dependencies that do not declare this mirror."),
        ["MirrorOrigin"] = ("origin（GitHub 官方源）", "origin (GitHub, official)"),
        ["MirrorAtomGit"] = ("atomgit（AtomGit 镜像）", "atomgit (AtomGit mirror)"),
        ["MirrorGitee"] = ("gitee（Gitee 镜像）", "gitee (Gitee mirror)"),
        ["MirrorGithub"] = ("github（官方源）", "github (official)"),
        ["MirrorTencent"] = ("tencent（腾讯云镜像）", "tencent (Tencent Cloud mirror)"),
        // Extra clause appended to a mirror's label when the engine only honors it for one thing.
        // Parentheses differ per language on purpose: Chinese uses full-width ones with no leading
        // space, English uses half-width ones preceded by a space.
        ["MirrorNoteAndroidGradle"] = ("（仅用于 Android Gradle）", " (Android Gradle only)"),
        ["MirrorStoragePrefix"] = ("写入位置", "Writes"),
        ["Apply"] = ("应用", "Apply"),
        ["ImportEngine"] = ("导入引擎", "Import engine"),
        ["Channel"] = ("通道", "Channel"),
        ["SetDefault"] = ("设为默认", "Set default"),
        ["VerifyEngine"] = ("验证", "Verify"),
        ["Repair"] = ("修复", "Repair"),
        ["Uninstall"] = ("卸载", "Uninstall"),
        // Confirmation prompts and consequence hints. The uninstall wording used to be a C# inline
        // ternary; it lives here now so both languages are editable in one place.
        ["UninstallPrompt"] = ("卸载 Axmol {0}？安装文件会保留到数据目录的 trash 中，项目文件不受影响。", "Uninstall Axmol {0}? Installation files are retained in the data directory's trash folder. Project files are preserved."),
        ["RepairPrompt"] = ("重新下载并覆盖 Axmol {0} 的引擎文件？使用此引擎的项目会被重置为“未构建”。", "Re-download and overwrite the Axmol {0} engine files? Projects using this engine are reset to Not built."),
        ["RepairHint"] = ("重新下载并覆盖整棵引擎树，使用此引擎的项目会回到“未构建”", "Re-downloads and overwrites the whole engine tree; projects using it go back to Not built"),
        ["RemoveProjectHint"] = ("把项目移出 Hub 列表，磁盘上的项目文件保留", "Removes the project from Hub's list; the project files on disk are kept"),
        ["RemoveEngineHint"] = ("把引擎移出 Hub 列表，磁盘上的引擎目录保留", "Removes the engine from Hub's list; the engine directory on disk is kept"),
        ["SwitchDataRootPrompt"] = ("把数据目录切换到 {0}？Hub 会重建工作区并清空当前页面缓存。", "Switch the data directory to {0}? Hub rebuilds the workspace and clears the current page cache."),
        ["ToolsTitle"] = ("平台构建支持", "Platform build support"),
        ["ToolsHint"] = ("按引擎版本管理平台模块和配套工具。", "Manage platform modules and tools for each engine version."),
        ["ToolsNote"] = ("MSVC 使用微软官方安装器，需要 Windows 管理员授权。", "MSVC uses Microsoft's installer and requires Windows administrator approval."),
        ["Component"] = ("组件", "Component"),
        ["Status"] = ("状态", "Status"),
        ["Details"] = ("版本与目录", "Version and location"),
        ["Verify"] = ("重新检测", "Verify"),
        ["InstallTools"] = ("安装基础工具", "Install tools"),
        ["RunEngineSetup"] = ("运行引擎 setup.ps1", "Run engine setup.ps1"),
        ["EngineSetupHint"] = ("工具链由引擎自己安装到引擎目录的 tools/external。这一步会写入用户级 PATH 与 AX_ROOT，并可能请求提权（UAC）——与引擎官方流程一致。", "The engine installs its own toolchain into <engine>/tools/external. This writes the user PATH and AX_ROOT and may request elevation (UAC) — the same as the engine's official flow."),
        ["BuildEngine"] = ("构建引擎库", "Build engine"),
        ["Build engine"] = ("构建引擎", "Build engine"),
        ["BuildEngineConfirm"] = ("开始构建引擎", "Build engine"),
        ["EngineBuildConfig"] = ("构建配置", "Build configuration"),
        ["EngineBuildCost"] = ("将把引擎编译成项目可复用的预编译库（Release 为优化构建）。这一步耗时数分钟到数十分钟并占用数 GB 磁盘；缺少工具链时可能触发引擎 setup。", "Compiles the engine into prebuilt libraries projects can reuse (Release is optimized). This takes many minutes and several GB of disk, and may trigger engine setup when tools are missing."),
        ["PrebuiltStatus"] = ("预编译引擎库", "Prebuilt engine libraries"),
        ["PrebuiltNone"] = ("尚未构建", "Not built"),
        ["PrebuiltReadyFormat"] = ("{0} → {1}（就绪）", "{0} → {1} (ready)"),
        ["PrebuiltStaleFormat"] = ("{0} → {1}（需重新构建）", "{0} → {1} (rebuild required)"),
        ["PrebuiltUnsupportedHost"] = ("此宿主无法使用预编译库（仅 Windows 构建目标支持链接预编译引擎）。", "Prebuilt libraries are unavailable on this host (only Windows build targets can link the prebuilt engine)."),
        ["PrebuiltSettings"] = ("预编译库设置", "Prebuilt library settings"),
        ["UsePrebuilt"] = ("使用预编译引擎库", "Use prebuilt engine libraries"),
        ["PrebuiltHint"] = ("仅 Windows 构建目标可用；需先在引擎页构建引擎，且目标与配置必须一致。", "Available for Windows build targets only; build the engine on the Engines page first and keep the target and configuration identical."),
        ["PrebuiltReadyHint"] = ("该引擎已有预编译库，目标与配置一致时会直接链接。", "This engine has a prebuilt build; builds link it when the target and configuration match."),
        ["PrebuiltNotBuiltHint"] = ("该引擎尚未构建预编译库；勾选后构建会失败，直到在引擎页构建它。", "This engine has no prebuilt build yet; builds will fail until you build it on the Engines page."),
        ["PrebuiltUnavailable"] = ("此项目使用预编译引擎库，但引擎那一份还不可用。", "This project uses prebuilt engine libraries, but the engine's build is not usable."),
        ["PrebuiltUnavailableFormat"] = ("目标 {0} · 配置 {1}", "Target {0} · configuration {1}"),
        ["PrebuiltUnavailableAction"] = ("请到引擎页为同一目标与配置构建引擎，或关闭该项目的预编译库选项。", "Build the engine on the Engines page for the same target and configuration, or turn off prebuilt libraries for this project."),
        ["PrebuiltReasonNotBuilt"] = ("该引擎尚未构建。", "The engine has not been built."),
        ["PrebuiltReasonConfiguration"] = ("引擎构建里没有该配置的库。", "The engine build has no libraries for this configuration."),
        ["PrebuiltReasonPlatform"] = ("该目标平台不支持预编译库（仅 Windows）。", "Prebuilt libraries are not supported for this target (Windows only)."),
        ["PrebuiltReasonEngineChanged"] = ("引擎安装已变更，预编译库可能过期。", "The engine installation changed; its prebuilt libraries may be stale."),
        ["PrebuiltReasonContents"] = ("引擎构建目录不完整。", "The engine build directory is incomplete."),
        ["PrebuiltReasonTarget"] = ("引擎构建的目标与当前项目不一致。", "The engine was built for a different target than this project."),
        ["PrebuiltSaved"] = ("预编译库设置已保存；请重新构建项目。", "Prebuilt settings saved; rebuild the project."),
        ["OpenEnginesPage"] = ("打开引擎页", "Open Engines page"),
        ["InstallSdk"] = ("安装 Windows SDK", "Install Windows SDK"),
        ["InstallMsvc"] = ("安装 MSVC", "Install MSVC"),
        ["SettingsHint"] = ("按你的习惯设置语言、存储目录与编辑器。", "Choose your language, storage and editors."),
        ["Language"] = ("界面语言", "Interface language"),
        ["LanguageHint"] = ("切换立即生效，重启后保留。", "Applies immediately and is remembered."),
        ["Appearance"] = ("外观", "Appearance"),
        ["Theme"] = ("主题", "Theme"),
        ["ThemeHint"] = ("跟随系统时会随系统主题变化；也可以固定为浅色或深色。", "Follows the system theme, or pin light or dark."),
        ["ThemeSystem"] = ("跟随系统", "Follow system"),
        ["ThemeLight"] = ("浅色", "Light"),
        ["ThemeDark"] = ("深色", "Dark"),
        ["Storage"] = ("存储与项目", "Storage and projects"),
        ["DataDirectory"] = ("Hub 数据目录", "Hub data directory"),
        ["DataHint"] = ("引擎、工具链、缓存与日志存放于此。切换目录不会移动现有文件。", "Engines, tools, cache and logs. Changing directories does not move existing files."),
        ["DefaultProjectDirectory"] = ("默认项目目录", "Default project directory"),
        ["ProjectDirectoryHint"] = ("创建新项目时默认使用此目录。", "Default parent directory for new projects."),
        ["Editors"] = ("代码编辑器", "Code editors"),
        ["SelectEditor"] = ("选择程序", "Choose executable"),
        ["NotSelected"] = ("尚未选择", "Not selected"),
        ["EditorHint"] = ("选择已安装的编辑器，用于打开项目。", "Choose an installed editor to open projects."),
        ["DefaultEngine"] = ("默认引擎", "Default engine"),
        ["NoDefault"] = ("尚未安装引擎", "No engine installed"),
        ["LogTitle"] = ("活动与构建日志", "Activity and build log"),
        ["CopyError"] = ("复制错误", "Copy error"),
        ["CopyCode"] = ("复制代码", "Copy code"),
        ["OpenLogs"] = ("打开日志", "Open logs"),
        ["Cancel"] = ("取消", "Cancel"),
        // 对话框按钮。以前这三条在 HubDialog 里是**写死的中文**，于是英文界面里点开任何弹窗，
        // 按钮都是中文 —— 而"缺中文字体"那条提示恰恰要靠这个按钮收尾（见 CjkFontNotice）。
        ["Ok"] = ("确定", "OK"),
        ["Yes"] = ("是", "Yes"),
        ["No"] = ("否", "No"),
        ["Ready"] = ("准备就绪", "Ready"),
        ["Done"] = ("已完成", "completed"),
        ["Cancelled"] = ("已取消", "cancelled"),
        ["Failed"] = ("失败", "Failed"),
        ["Working"] = ("处理中", "Working"),
        ["Download"] = ("下载中", "Downloading"),
        ["EmptyProjects"] = ("还没有项目。创建第一个项目，开始开发。", "No projects yet. Create your first project to get started."),
        ["EmptyEngines"] = ("还没有引擎。安装或导入 Axmol。", "No engines yet. Install or import Axmol."),
        ["Installed"] = ("已安装", "Installed"),
        ["Missing"] = ("未安装", "Missing"),
        ["Broken"] = ("需要修复", "Broken"),
        ["Unknown"] = ("未检测", "Unknown"),
        ["Checking"] = ("检测中", "Checking"),
        ["Installing"] = ("安装中", "Installing"),
        ["UpdateAvailable"] = ("有更新", "Update available"),
        ["Not built"] = ("未构建", "Not built"),
        ["Succeeded"] = ("构建成功", "Succeeded"),
        ["Configured"] = ("已配置", "Configured"),
        ["Configuring"] = ("配置中", "Configuring"),
        ["Building"] = ("构建中", "Building"),
        ["Select a project first."] = ("请先选择项目。", "Select a project first."),
        ["Select an engine first."] = ("请先选择引擎。", "Select an engine first."),
        ["Install or import an engine first."] = ("请先安装或导入引擎。", "Install or import an engine first."),
        ["Build successfully before Run."] = ("请先成功构建，再运行。", "Build successfully before Run."),
        ["Select VS Code executable in Settings first."] = ("请先在设置中选择 VS Code。", "Select VS Code executable in Settings first."),
        ["Select Visual Studio devenv.exe in Settings first."] = ("请先在设置中选择 Visual Studio。", "Select Visual Studio devenv.exe in Settings first."),
        ["Verify toolchains"] = ("检测工具链", "Verify toolchains"),
        ["Import engine"] = ("导入引擎", "Import engine"),
        ["Install official engine"] = ("安装官方引擎", "Install official engine"),
        ["Create project"] = ("创建项目", "Create project"),
        ["Open project"] = ("添加项目", "Add project"),
        ["Configure CMake"] = ("配置 CMake", "Configure CMake"),
        ["Build project"] = ("构建项目", "Build project"),
        ["Run project"] = ("运行项目", "Run project"),
        ["Install managed tools"] = ("安装基础工具", "Install tools"),
        ["Install Windows SDK"] = ("安装 Windows SDK", "Install Windows SDK"),
        ["Install MSVC Build Tools"] = ("安装 MSVC", "Install MSVC"),
        ["Set default engine"] = ("设置默认引擎", "Set default engine"),
        ["Verify engine"] = ("验证引擎", "Verify engine"),
        ["Remove engine from list"] = ("移出引擎列表", "Remove engine from list"),
        ["Remove project from list"] = ("移出项目列表", "Remove project from list"),
        ["Open project folder"] = ("打开项目目录", "Open project folder"),
        ["Open engine folder"] = ("打开引擎目录", "Open engine folder"),
        ["Open VS Code"] = ("打开 VS Code", "Open VS Code"),
        ["Open Visual Studio"] = ("打开 Visual Studio", "Open Visual Studio"),
        ["Select Axmol engine root"] = ("选择 Axmol 引擎目录", "Select Axmol engine root"),
        ["Select Axmol project folder"] = ("选择 Axmol 项目目录", "Select Axmol project folder"),
        ["Select parent location"] = ("选择项目父目录", "Select parent directory"),
        ["Select data directory"] = ("选择 Hub 数据目录", "Select Hub data directory"),
        ["Select default project directory"] = ("选择默认项目目录", "Select default project directory"),
        ["MsvcActive"] = ("微软安装器运行中，请批准 Windows 授权；取消请使用安装器界面。", "Microsoft installer is running. Approve Windows UAC; cancel in the installer."),
        ["Cancelling"] = ("正在取消，请等待进程停止后再关闭。", "Cancelling. Close again when the process stops."),
        ["ErrorHint"] = ("操作失败，详细原因已记录在日志中。", "Operation failed. Details are recorded in the log."),
        ["OperationFailed"] = ("操作失败", "Operation failed"),
        ["BuildProgress"] = ("构建进度", "Build progress"),
        ["BuildPreparing"] = ("准备构建", "Preparing build"),
        ["BuildConfiguring"] = ("配置项目", "Configuring project"),
        ["BuildCompiling"] = ("编译代码", "Compiling code"),
        ["BuildPackaging"] = ("打包应用", "Packaging application"),
        ["BuildVerifying"] = ("校验产物", "Verifying output"),
        ["BuildElapsed"] = ("已用时间", "Elapsed"),
        ["BuildProgressHint"] = ("百分比显示当前编译阶段的进度；配置、打包和校验时显示活动进度。", "Percentage shows the current compilation stage. Configuration, packaging and verification use an activity indicator."),
        ["ProjectAlreadyExists"] = ("项目目录已存在，无法创建同名项目。", "The project destination already exists. Cannot create a project at the same location."),
        ["ProjectAlreadyExistsAction"] = ("请修改项目名称或选择其他目录。若要使用现有项目，请点击“添加已有项目”。", "Change the project name or choose another directory. To use the existing project, click Add existing project."),
        ["EngineMissing"] = ("项目所需引擎未安装，请前往引擎页面安装或导入。", "Required engine is missing. Install or import it on the Engines page."),
        ["Managed MSVC v143"] = ("MSVC v143", "MSVC v143"),
        ["Managed Windows SDK"] = ("Windows SDK", "Windows SDK"),
        ["Axmol shader compiler"] = ("着色器编译器", "Shader compiler"),
        ["Python (optional for Windows C++)"] = ("Python（Windows C++ 可选）", "Python (optional for Windows C++)"),
        ["Repair engine"] = ("修复引擎", "Repair engine"),
        ["Uninstall engine"] = ("卸载引擎", "Uninstall engine"),
        ["DataChanged"] = ("数据目录已切换", "Data directory changed"),
        ["DefaultProjectsChanged"] = ("默认项目目录已保存", "Default project directory saved"),
        ["PageNotMigrated"] = ("该页面尚未迁移到 Avalonia 版（P5 进行中）。", "This page has not been migrated to the Avalonia build yet (P5 in progress)."),
        ["WaitForOperation"] = ("请先等当前操作结束或取消它，再切换数据目录。", "Wait for the active operation to finish or cancel it before changing the data directory."),
        ["LocalPathRequired"] = ("选中的位置没有本地路径，请选择本机磁盘上的位置。", "The selected location has no local path. Choose a location on this PC."),
        ["Select devenv.exe"] = ("选择 devenv.exe", "Select devenv.exe"),
        ["Select Code.exe"] = ("选择 Code.exe", "Select Code.exe"),
        ["Choose devenv.exe"] = ("请选择 devenv.exe。", "Choose devenv.exe."),
        ["Choose Code.exe"] = ("请选择 Code.exe。", "Choose Code.exe."),
        ["StartupFailed"] = ("Axmol Hub 启动失败", "Axmol Hub failed to start"),
        // 更新检查（Velopack 自更新）。"检查更新"按钮在设置页，启动时也会自动静默检查一次。
        ["Updates"] = ("软件更新", "Software update"),
        ["UpdatesHint"] = ("检查 Axmol Hub 的新版本。只有安装版才会自动更新。", "Check for a new version of Axmol Hub. Only installed copies update automatically."),
        ["CurrentVersion"] = ("当前版本", "Current version"),
        ["CheckForUpdates"] = ("检查更新", "Check for updates"),
        ["CheckingUpdate"] = ("正在检查更新…", "Checking for updates…"),
        ["UpdateUpToDate"] = ("已是最新版本。", "You're up to date."),
        ["UpdateNotInstalled"] = ("当前是开发版或便携版，无法自动更新。", "This is a development or portable copy, so it can't update itself."),
        ["UpdateFailed"] = ("检查更新失败，请稍后重试。", "Couldn't check for updates. Try again later."),
        // 「有可用更新」不用弹窗，只在设置页导航项上点一个红点（见 Hub.NotificationDot）；红点只负责
        // 「去看设置」，版本号、下载进度与操作都在设置页的更新卡片里。
        ["UpdateDotTooltip"] = ("有可用更新", "Update available"),
        ["UpdateCheckHint"] = ("点「检查更新」查看是否有新版本。", "Click \"Check for updates\" to see if a newer version exists."),
        ["AutoDownloadUpdates"] = ("自动下载更新", "Auto-download updates"),
        ["UpdateReady"] = ("发现新版本 {0}。", "Version {0} is available."),
        ["DownloadAndRestart"] = ("下载并重启", "Download & restart"),
        ["UpdateDownloading"] = ("正在下载更新… {0}%", "Downloading update… {0}%"),
        // 进度条/状态行的悬停提示。{0} 是已格式化好的速率（"2.4 MB/s"），单位不随语言变化。
        ["UpdateDownloadSpeed"] = ("下载速度：{0}", "Download speed: {0}"),
        ["UpdateReadyToRestart"] = ("更新已就绪，重启完成更新。", "Update ready — restart to finish."),
        ["RestartNow"] = ("立即重启", "Restart now"),
        // 故意不带 {0}：后面要拼的是异常原文，可能含花括号，string.Format 会抛 FormatException。
        ["UpdateDownloadFailed"] = ("更新下载失败：", "Couldn't download the update: "),
        // 内置 AI 助手。协议基线是 OpenAI 兼容，首期 provider = OrcaRouter + 自定义。
        ["Assistant"] = ("AI 助手", "AI assistant"),
        ["AssistantHint"] = ("向助手提问 Axmol 相关问题。模型由你配置的 provider 提供。", "Ask the assistant about Axmol. Answers come from the provider you configure."),
        ["AssistantEmpty"] = ("开始新的对话。", "Start a new conversation."),
        ["NewConversation"] = ("新建对话", "New conversation"),
        ["DeleteConversation"] = ("删除对话", "Delete conversation"),
        ["SearchConversations"] = ("搜索对话", "Search conversations"),
        ["NoSearchResults"] = ("没有匹配的对话。", "No matching conversations."),
        ["ConversationActions"] = ("对话操作", "Conversation actions"),
        ["Conversation"] = ("对话", "Conversation"),
        ["NoConversations"] = ("还没有对话。", "No conversations yet."),
        ["NoAvailableChatModels"] = ("请先在设置中鉴权并添加可用模型。", "Authenticate a provider and add an available model in Settings first."),
        ["Send"] = ("发送", "Send"),
        ["Stop"] = ("停止", "Stop"),
        ["InputPlaceholder"] = ("输入消息，Enter 发送，Shift+Enter 换行", "Type a message. Enter to send, Shift+Enter for a newline"),
        ["Provider"] = ("模型提供商", "Provider"),
        // 设置页中 AI 模型 provider 管理卡片的标题与说明。
        ["ModelProviders"] = ("AI 模型提供商", "AI Model providers"),
        ["ModelProvidersHint"] = ("助手使用的模型接口。「添加提供商」可从内置预设中挑选（OrcaRouter、OpenAI、DeepSeek、Ollama…），已配置的提供商在此管理密钥与模型；助手页只负责选择用哪一个。", "The endpoints the assistant can use. \"Add provider\" picks from built-in presets (OrcaRouter, OpenAI, DeepSeek, Ollama …); keys and models for the ones you configured are managed here, while the assistant page only chooses between them."),
        // 助手页模型提示，{0} = 提供商名称，{1} = 模型名称。
        ["ActiveModelFormat"] = ("当前模型：{0} · {1}", "Current model: {0} · {1}"),
        ["NoProvider"] = ("尚未配置模型提供商。", "No model provider is configured yet."),
        ["ApiKey"] = ("API 密钥", "API key"),
        ["ApiKeyHint"] = ("密钥保存在操作系统的凭据存储中，不会写入配置文件或日志。", "The key is kept in the OS credential store, never written to config files or logs."),
        ["ApiKeyPlatformUnsupported"] = ("当前平台尚不支持安全保存密钥（Windows 使用 DPAPI；macOS/Linux 待补）。", "Secure key storage is not available on this platform yet (Windows uses DPAPI; macOS/Linux are pending)."),
        ["ApiKeyRequired"] = ("该提供商需要 API 密钥。", "This provider requires an API key."),
        ["SaveApiKey"] = ("保存密钥", "Save key"),
        // affiliate 披露：OrcaRouter 参与 OSS 计划，通过本项目的推荐链接注册，Simdsoft 可获得分成，所得收入全部用于 Axmol 引擎及相关工具的研发（见规划 D5）。
        ["AffiliateDisclosure"] = ("通过本项目的推荐链接注册 {0}，Simdsoft 可获得分成，所得收入将全部用于 Axmol 引擎及相关工具的研发。", "Signing up for {0} through this project's referral link earns Simdsoft a commission, all of which goes toward developing the Axmol engine and its tooling."),
        ["ViewReferral"] = ("了解详情", "Learn more"),
        ["ChatFailed"] = ("助手请求失败：", "Assistant request failed: "),
        ["ChatCancelled"] = ("已停止。", "Stopped."),
        ["You"] = ("你", "You"),
        // provider 管理（custom provider = 用户自带 endpoint，接入本地模型的主要途径）。
        ["AddProvider"] = ("添加提供商", "Add provider"),
        ["EditProvider"] = ("编辑提供商", "Edit provider"),
        ["RemoveProvider"] = ("移除提供商", "Remove provider"),
        ["AddCustomProvider"] = ("添加自定义提供商", "Add custom provider"),
        ["EditProviderTitle"] = ("编辑提供商", "Edit provider"),
        ["ProviderName"] = ("名称", "Name"),
        ["ProviderBaseUrl"] = ("接口地址", "Base URL"),
        ["ProviderBaseUrlHint"] = ("OpenAI 兼容的接口地址，例如 https://api.openai.com/v1，本地模型如 http://localhost:11434/v1。", "OpenAI-compatible base URL, e.g. https://api.openai.com/v1; for a local model, http://localhost:11434/v1."),
        ["ProviderModel"] = ("模型名称", "Model"),
        ["ModelsCount"] = ("模型（{0}）", "Models ({0})"),
        ["CurrentModelSummary"] = ("当前使用：{0}", "In use: {0}"),
        ["ToggleModelList"] = ("展开或折叠模型列表", "Expand or collapse model list"),
        ["ProviderModelHint"] = ("提供商使用的默认模型，例如 gpt-4o-mini、orcarouter/auto、llama3。", "Default model for this provider, e.g. gpt-4o-mini, orcarouter/auto, llama3."),
        ["ProviderNameRequired"] = ("请填写提供商名称。", "Enter a provider name."),
        ["ProviderBaseUrlInvalid"] = ("接口地址无效：请填写完整的 http/https 地址。", "Invalid base URL: enter a full http/https address."),
        ["ProviderModelRequired"] = ("请填写模型名称。", "Enter a model name."),
        ["ProviderBuiltInReadOnly"] = ("内置提供商不能移除；如需其他接口，请添加自定义提供商。", "Built-in providers can't be removed. To use another endpoint, add a custom provider."),
        ["ProviderRemoved"] = ("已移除提供商。", "Provider removed."),
        ["ProviderBuiltInLockedHint"] = ("内置提供商的接口地址与名称由清单固定，可修改模型和密钥。", "A built-in provider's base URL and name come from the manifest; its model and key can be changed."),
        ["RemoveProviderConfirm"] = ("移除后该提供商的密钥也会删除，且无法恢复。", "Removing it also deletes its stored API key. This cannot be undone."),
        // provider 预设选择器（对齐 GitHub Copilot 的「列表 + 可搜索添加」交互）。
        ["ProviderPickerHint"] = ("选择要接入的模型提供商。可搜索名称或说明；接入清单外的私有接口请选「自定义接口」。", "Pick a model provider to add. Search by name or description; for a private endpoint that isn't listed, choose \"Custom endpoint\"."),
        ["ProviderSearchHint"] = ("搜索提供商", "Search providers"),
        ["ProviderSearchNoMatch"] = ("没有匹配的提供商。试试更短的关键词，或选择「自定义接口」。", "No matching provider. Try a shorter term, or choose \"Custom endpoint\"."),
        ["ProviderCustomRow"] = ("自定义接口", "Custom endpoint"),
        ["ProviderCustomRowHint"] = ("手动填写 OpenAI 兼容的接口地址与模型，适用于自建网关或局域网内的本地模型。", "Enter an OpenAI-compatible base URL and model by hand — for a self-hosted gateway or a local model on another machine."),
        ["ProviderAlreadyAdded"] = ("该提供商已在列表中。", "That provider is already in the list."),
        // 认证方式与账号（对齐 opencode 的 account 模型：一份凭据 = 一个账号，不分来源）。
        ["AuthMethod"] = ("认证方式", "Sign-in method"),
        ["AuthMethodApiKey"] = ("API 密钥", "API key"),
        ["AuthMethodOAuth"] = ("浏览器登录", "Sign in with browser"),
        ["AuthMethodNone"] = ("无需认证", "No sign-in needed"),
        ["AuthMethodNoneHint"] = ("本地接口不需要密钥，可以直接使用。", "A local endpoint needs no key and works as-is."),
        ["AuthOAuthSignIn"] = ("使用 {0} 登录", "Sign in with {0}"),
        ["AuthOAuthHint"] = ("将在浏览器中打开 {0} 的授权页面；完成授权后密钥会自动保存，无需手动复制。", "Opens {0}'s authorization page in your browser. The key is saved automatically once you approve — nothing to copy."),
        ["AuthOAuthPending"] = ("正在等待浏览器授权…", "Waiting for authorization in the browser…"),
        ["AuthOAuthSucceeded"] = ("已登录并保存密钥。", "Signed in; the key has been saved."),
        ["AuthOAuthFailed"] = ("登录失败：", "Sign-in failed: "),
        ["AuthOAuthCancelled"] = ("已取消登录。", "Sign-in cancelled."),
        ["AuthOAuthScopeRejected"] = ("授权返回的权限范围比请求的更宽（{0}），已拒绝该密钥。请在授权页面仅勾选接口访问权限。", "The granted scope ({0}) is wider than the one requested, so the key was refused. On the consent page, grant API access only."),
        ["AuthOAuthNoBrowser"] = ("无法自动打开浏览器，请手动访问下面的地址：", "Could not open a browser automatically; open this address by hand:"),
        ["AuthOAuthPlatformUnsupported"] = ("当前平台尚不支持安全保存密钥，无法完成登录。", "Secure key storage is not available on this platform yet, so sign-in cannot complete."),
        // 两种登录入口同时出现时，中间的分隔文案。
        ["AuthOrSeparator"] = ("或", "or"),
        // "Active" survives the account list's removal because the *model* rows reuse it to mark the model in
        // use. The key kept its old name rather than being renamed to ModelActive: HubTexts is bilingual data,
        // not something to churn, and a rename would have touched two languages to say nothing.
        ["AccountActive"] = ("使用中", "Active"),
        ["Affiliate"] = ("推荐", "Referral"),
        ["Add"] = ("添加", "Add"),
        ["Save"] = ("保存", "Save"),
        // 分组列表（每个已配置的 provider 各成一组、全部展开）与其中的模型子列表。
        ["ProviderInUse"] = ("当前", "Current"),
        ["ProviderBuiltInTag"] = ("内置", "Built-in"),
        ["ProviderCustomTag"] = ("自定义", "Custom"),
        ["ProviderNoCredential"] = ("此提供商无需密钥，可直接使用。", "This provider needs no key and works as-is."),
        ["RemoveProviderIcon"] = ("移除", "Remove"),
        ["Models"] = ("模型", "Models"),
        ["ModelsHint"] = ("同一提供商可保存多个模型，标为「使用中」的是默认模型；每个对话也可单独选择模型。", "A provider can hold several models; \"In use\" is its default, and each conversation can choose a model independently."),
        ["AddModel"] = ("添加模型", "Add model"),
        ["RefreshModels"] = ("刷新", "Refresh"),
        ["RefreshModelsHint"] = ("从提供商重新拉取可用模型列表。", "Fetch the available model list from the provider again."),
        // 拉取结果。三种结局分开写而不是一句话带过：「问到了但一个都没有」和「压根没问到」在用户那里是
        // 完全不同的两件事——前者要去检查账号权限或本地服务，后者要检查网络，合写成一句就等于没告诉
        // 用户该做什么。
        ["ModelsRefreshing"] = ("正在拉取模型列表…", "Fetching the model list…"),
        ["ModelsFetched"] = ("已拉取 {0} 个模型。", "Fetched {0} models."),
        ["ModelsFetchedEmpty"] = ("该提供商没有返回任何模型。", "The provider returned no models."),
        ["ModelsFetchFailed"] = ("未能拉取模型列表，保留原有列表。", "Could not fetch the model list; the existing list was kept."),
        ["ModelUse"] = ("使用此模型", "Use this model"),
        ["ModelEnabledHint"] = ("在聊天模型选择器中启用或隐藏此模型。", "Show or hide this model in the chat model picker."),
        ["ModelRemove"] = ("移除该模型", "Remove this model"),
        ["ModelRemoveConfirm"] = ("将从本机列表移除该模型，提供商与密钥不受影响。", "Removes this model from the local list. The provider and its keys are unaffected."),
        ["ModelAdded"] = ("已添加模型。", "Model added."),
        ["ModelRemoved"] = ("已移除模型。", "Model removed."),
        ["ModelDuplicated"] = ("该模型已在列表中。", "That model is already in the list."),
        ["ModelNameRequired"] = ("请填写模型名称。", "Enter a model name."),
        ["ModelNamePlaceholder"] = ("模型名称，例如 gpt-5.1-codex-mini", "Model name, e.g. gpt-5.1-codex-mini"),
        ["AddModelTitle"] = ("添加模型", "Add model"),
        ["OpenModelCatalog"] = ("浏览模型目录", "Browse catalog"),
        ["ModelCatalogTitle"] = ("{0} 模型目录", "{0} model catalog"),
        ["ModelCatalogHint"] = ("双击模型即可启用；可连续选择多个模型。", "Double-click models to enable them; you can choose several."),
        ["ModelCatalogSearchHint"] = ("搜索模型名称", "Search model names"),
        ["ModelCatalogEmpty"] = ("缓存目录为空。点击刷新从提供商获取模型。", "The cached catalog is empty. Refresh to fetch models from the provider."),
        ["ModelCatalogRefreshUnavailable"] = ("请先完成提供商鉴权后再刷新模型目录。", "Authenticate this provider before refreshing its model catalog."),
        ["ModelCatalogNoMatch"] = ("没有匹配的模型。", "No matching models."),
        ["ModelCatalogEnabled"] = ("已启用模型：{0}", "Enabled model: {0}"),
        ["ModelCatalogEnableFailed"] = ("无法启用该模型，请刷新目录后重试。", "Could not enable this model. Refresh the catalog and try again."),
        ["ModelCatalogEnabledState"] = ("已启用", "Enabled"),
        ["ModelCatalogDisabledState"] = ("双击启用", "Double-click to enable"),
        ["CloseModelCatalog"] = ("关闭", "Close"),
        ["NoEnabledModels"] = ("尚未启用模型。浏览模型目录，或手动添加模型。", "No models enabled. Browse the catalog or add a model manually."),
        ["NoModels"] = ("尚未添加模型。", "No models added yet."),
        // 鉴权状态与断开。对勾 = 该 provider 已鉴权（有一份凭据，不分来源）。术语统一用「鉴权 / 链接」。
        //
        // 这些文案在「一个 provider 一份凭据」之后改过一次：原来写的是「全部账号」，那是多账号模型留下的
        // 说法，现在一个 provider 只有一份凭据，说「全部」反而会让用户以为还有别的要清。
        ["ProviderConnected"] = ("已鉴权", "Authenticated"),
        ["ProviderNotConnected"] = ("未鉴权", "Not authenticated"),
        ["DisconnectProviderConfirm"] = ("将删除该提供商在本机保存的密钥，提供商本身保留，可随时重新鉴权。此操作无法恢复。", "Deletes the key saved for this provider on this machine. The provider itself stays and can be reauthenticated at any time. This cannot be undone."),
        ["ProviderDisconnected"] = ("已断开鉴权并清除本地密钥。", "Disconnected; local key cleared."),
        ["ProviderNothingToDisconnect"] = ("该提供商没有已保存的密钥。", "This provider has no saved key."),
        ["ProviderPinnedHint"] = ("默认提供商不能移除（移除后会在下次启动时自动恢复）；可以断开鉴权清除本地密钥。", "The default provider can't be removed — it would be restored on the next launch. You can disconnect it to clear local keys."),

        // 折叠态下那一行摘要。只剩模型数：账号数在一对一之后恒为 0 或 1，而「1 个账号」是个没有信息量的
        // 数字——连接状态由名称旁边的对勾说，不需要文字再说一遍。
        ["SummaryModelCount"] = ("{0} 个已配置模型", "{0} configured models"),
        ["SummaryModelCountOne"] = ("1 个已配置模型", "1 configured model"),

        // ── 鉴权对话框 ──
        // 列表里只有一个按钮：未鉴权时叫「鉴权」，已鉴权时叫「断开鉴权」。真正的输入发生在对话框里，
        // 所以列表页永远看不到输入框。
        ["Authenticate"] = ("鉴权", "Authenticate"),
        ["DisconnectProvider"] = ("断开鉴权", "Disconnect"),
        ["AuthDialogTitle"] = ("鉴权 {0}", "Authenticate {0}"),
        ["AuthDialogHint"] = ("该提供商支持以下鉴权方式，请选择一种。", "This provider supports the following methods. Pick one."),
        ["AuthMethodLoginOption"] = ("用 {0} 账号登录", "Sign in with a {0} account"),
        ["AuthMethodKeyOption"] = ("粘贴已有密钥", "Paste an existing key"),
        ["Next"] = ("下一步", "Next"),
        ["Back"] = ("上一步", "Back"),
        ["AuthKeyStepTitle"] = ("输入密钥", "Enter your key"),
        ["AuthKeyStepHint"] = ("密钥只保存在本机。确定前会向 {0} 校验一次。", "The key is stored on this machine only. It is checked against {0} before it is saved."),
        ["AuthKeyStepHintNoCheck"] = ("密钥只保存在本机。", "The key is stored on this machine only."),
        ["AuthKeyChecking"] = ("正在校验…", "Checking…"),
        ["AuthKeyRejected"] = ("{0} 拒绝了该密钥，请检查后重试。", "{0} rejected this key. Check it and try again."),
        // 校验请求本身失败（离线 / 端点不可达）时**照常保存**：把「问不到」说成「密钥无效」会让用户在
        // 酒店 Wi-Fi 上怎么也连不上。这个区分与 KeyCheckOutcome 的四态是一一对应的。
        ["AuthKeyUnreachable"] = ("无法向 {0} 校验该密钥（网络或端点不可用），将直接保存。", "Could not check the key with {0} (network or endpoint unavailable); saving it as typed."),
        ["AuthKeyAccepted"] = ("密钥有效。", "The key is valid."),
        ["AuthDone"] = ("鉴权成功。", "Authenticated."),
        ["AuthDialogCancelled"] = ("已取消鉴权。", "Authentication cancelled."),
        ["AuthSecretsUnsupported"] = ("当前平台没有可用的密钥存储，无法保存鉴权信息。", "This platform has no secret store available, so authentication cannot be saved."),

        // 移除 provider 时的自动断开。确认框必须说明凭据会一起没了，否则「移除」看起来只影响列表。
        ["RemoveProviderWithCredentials"] = ("将同时删除该提供商在本机保存的 {0} 个账号与密钥。此操作无法恢复。", "Also deletes the {0} account(s) and key(s) saved for this provider on this machine. This cannot be undone."),
        ["RemoveProviderIconHint"] = ("移除该提供商", "Remove this provider"),
    };
}
